//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class altkategori
    {
        public altkategori()
        {
            this.uruns = new HashSet<urun>();
        }
    
        public int Altkategori_ID { get; set; }
        public string Altkategori_ismi { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual ICollection<urun> uruns { get; set; }
    }
}
