//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori
    {
        public kategori()
        {
            this.altkategoris = new HashSet<altkategori>();
        }
    
        public int Kategori_ID { get; set; }
        public string Kategori_ismi { get; set; }
        public Nullable<int> Restoran_ID { get; set; }
    
        public virtual ICollection<altkategori> altkategoris { get; set; }
        public virtual restoran restoran { get; set; }
    }
}
