//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masa
    {
        public masa()
        {
            this.musteris = new HashSet<musteri>();
            this.rezervasyons = new HashSet<rezervasyon>();
        }
    
        public int Masa_ID { get; set; }
        public Nullable<int> Restoran_ID { get; set; }
        public Nullable<int> Masa_kisiSayisi { get; set; }
        public bool Masa_bosmu { get; set; }
        public Nullable<int> Masa_numarasi { get; set; }
    
        public virtual restoran restoran { get; set; }
        public virtual ICollection<musteri> musteris { get; set; }
        public virtual ICollection<rezervasyon> rezervasyons { get; set; }
    }
}
