//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AhmetEntities2 : DbContext
    {
        public AhmetEntities2()
            : base("name=AhmetEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<altkategori> altkategoris { get; set; }
        public DbSet<ilce> ilces { get; set; }
        public DbSet<kategori> kategoris { get; set; }
        public DbSet<masa> masas { get; set; }
        public DbSet<musteri> musteris { get; set; }
        public DbSet<odeme> odemes { get; set; }
        public DbSet<restoran> restorans { get; set; }
        public DbSet<rezervasyon> rezervasyons { get; set; }
        public DbSet<sehir> sehirs { get; set; }
        public DbSet<semt> semts { get; set; }
        public DbSet<sipari> siparis { get; set; }
        public DbSet<sistemurun> sistemuruns { get; set; }
        public DbSet<urun> uruns { get; set; }
        public DbSet<yonetici> yoneticis { get; set; }
        public DbSet<yorum> yorums { get; set; }
    }
}
