//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyon
    {
        public int Rezervasyon_ID { get; set; }
        public Nullable<int> Restoran_ID { get; set; }
        public Nullable<int> Masa_ID { get; set; }
        public Nullable<System.TimeSpan> Rezervasyon_zamani { get; set; }
        public Nullable<System.DateTime> Rezervasyon_gunu { get; set; }
        public Nullable<bool> onay { get; set; }
    
        public virtual masa masa { get; set; }
        public virtual restoran restoran { get; set; }
    }
}
