//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sipari
    {
        public int Siparis_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<int> Musteri_ID { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<bool> hazir { get; set; }
    }
}
