//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public urun()
        {
            this.yorums = new HashSet<yorum>();
        }
    
        public int Urun_ID { get; set; }
        public Nullable<int> Restoran_ID { get; set; }
        public Nullable<int> Altkategori_ID { get; set; }
        public string Urun_adi { get; set; }
        public double Urun_fiyati { get; set; }
        public string Urun_aciklamasi { get; set; }
        public Nullable<int> Urun_kalorisi { get; set; }
        public Nullable<int> Urun_pismeSuresi { get; set; }
        public string Urun_resmi { get; set; }
    
        public virtual altkategori altkategori { get; set; }
        public virtual restoran restoran { get; set; }
        public virtual ICollection<yorum> yorums { get; set; }
    }
}
