//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int Yorum_ID { get; set; }
        public string yorumlar { get; set; }
        public int urun_ID { get; set; }
        public Nullable<int> puan { get; set; }
        public Nullable<int> musteri_ID { get; set; }
        public Nullable<int> restoran_ID { get; set; }
    
        public virtual musteri musteri { get; set; }
        public virtual urun urun { get; set; }
    }
}
